### ISSUE TITLE
Unicode doesn't work

### ISSUE THREAD

**Issue by mallyvai** [KoffeinFlummi/Chronyk#9]
```
>>> import chronyk
>>> chronyk.Chronyk("2015-5-5")
<chronyk.chronyk.Chronyk instance at 0x7fc70d03c3b0>
>>> chronyk.Chronyk(u"2015-5-5")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mallyvai/.virtualenvs/webdev4/local/lib/python2.7/site-packages/chronyk/chronyk.py", line 77, in __init__
    raise TypeError("Invalid type specified.")
TypeError: Invalid type specified.

$ python --version
Python 2.7.6

$ pip show chronyk

---
Metadata-Version: 2.0
Name: Chronyk
Version: 0.9.1
Summary: A library for parsing human-written times and dates.
Home-page: https://github.com/KoffeinFlummi/PyGHI
Author: Felix "KoffeinFlummi" Wiegand
Author-email: koffeinflummi@gmail.com
[...]
```

**Comment by msoedov** [comment]
@mallyvai this library does not suppose to work with `Python 2.7.6`
https://github.com/KoffeinFlummi/Chronyk/blob/master/setup.py#L27-L29
